# Generated by Django 3.1.3 on 2024-11-30 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainNews',
            fields=[
                ('ranking', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('img_link', models.TextField(blank=True, null=True)),
                ('category', models.IntegerField(blank=True)),
            ],
            options={
                'db_table': 'Main_news',
                'managed': False,
            },
        ),
    ]
