# Generated by Django 3.1.3 on 2024-11-30 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_userfavoritekeywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoritekeywords',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
