# Generated by Django 3.1.3 on 2024-11-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_recentkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoritekeywords',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
