# Generated by Django 3.1.3 on 2024-11-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_userfavoritekeywords_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoritekeywords',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
